/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
//#include "stm32f407_xx.h"
#include "stm32f407_drivers.h"

#include <stdint.h>
#include<stdio.h>

int main(void)
{
   GPIO_Handle_t led;
   GPIO_PeriClockControl(GPIOD, ENABLE);
   led.pGPIOx=GPIOD;
   led.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_12;
   led.GPIO_PinConfig.GPIO_PinMode=GPIO_MODE_OUT;
   led.GPIO_PinConfig.GPIO_PinSpeed=GPIO_SPEED_MEDIUM;
   led.GPIO_PinConfig.GPIO_PinPuPdControl=GPIO_NO_PUPD;
   led.GPIO_PinConfig.GPIO_PinOPType=GPIO_OP_TYPE_PP;
   GPIO_Init(&led);
   while(1)
   {
	   GPIO_ToggleOutputPin(GPIOD,GPIO_PIN_NO_12);
	   uint8_t temp=GPIO_ReadFromInputPin(GPIOD,12);
	   printf("%dHH\n",temp);
	   for(volatile int i=0;i<300000;i++);
   }


}
