/*
 * led_button.c
 *
 *  Created on: Oct 10, 2025
 *      Author: karnati.ganesh
 */


/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
//#include "stm32f407_xx.h"
#include "stm32f407_drivers.h"

#include <stdint.h>
#include<stdio.h>

int main(void)
{
   GPIO_Handle_t led_bn;
   GPIO_PeriClockControl(GPIOD, ENABLE);
   led_bn.pGPIOx=GPIOA;
   led_bn.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_0;
   led_bn.GPIO_PinConfig.GPIO_PinMode=GPIO_MODE_IN;
   led_bn.GPIO_PinConfig.GPIO_PinSpeed=GPIO_SPEED_MEDIUM;
  // led_bn.GPIO_PinConfig.GPIO_PinOPType=GPIO_OP_TYPE_OD;
   GPIO_Init(&led_bn);
   while(1)
   {
	   if(GPIO_ReadFromInputPin(GPIOA,0))
	   GPIO_ToggleOutputPin(GPIOD,GPIO_PIN_NO_12);

   }


}
