/*
 * external_button.c
 *
 *  Created on: Oct 10, 2025
 *      Author: karnati.ganesh
 */
/*
 * led_button.c
 *
 *  Created on: Oct 10, 2025
 *      Author: karnati.ganesh
 */


/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
//#include "stm32f407_xx.h"
#include "stm32f407_drivers.h"

#include <stdint.h>
#include<stdio.h>

int main(void)
{
   GPIO_Handle_t button;
   GPIO_Handle_t led;
   GPIO_PeriClockControl(GPIOA, ENABLE);
   GPIO_PeriClockControl(GPIOE, ENABLE);
   led.pGPIOx=GPIOA;
   led.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_9;
   led.GPIO_PinConfig.GPIO_PinMode=GPIO_MODE_OUT;
   led.GPIO_PinConfig.GPIO_PinSpeed=GPIO_SPEED_MEDIUM;
   led.GPIO_PinConfig.GPIO_PinPuPdControl=GPIO_PIN_PU;
   led.GPIO_PinConfig.GPIO_PinOPType=GPIO_OP_TYPE_PP;
   button.pGPIOx=GPIOE;
      button.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_5;
      button.GPIO_PinConfig.GPIO_PinMode=GPIO_MODE_IN;
      button.GPIO_PinConfig.GPIO_PinSpeed=GPIO_SPEED_MEDIUM;
      button.GPIO_PinConfig.GPIO_PinPuPdControl=GPIO_PIN_PU;
   GPIO_Init(&led);
   GPIO_Init(&button);
   while(1)
   {
	   if(GPIO_ReadFromInputPin(GPIOE,5)==0)
	   {
		   for(volatile int i=0;i<300;i++);

	   GPIO_ToggleOutputPin(GPIOA,GPIO_PIN_NO_9);
   }

   }


}
